#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyFirstApp.Resource", IsApplication=true)]

namespace MyFirstApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int Flats_array = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int city_array = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int welcome_menu = 2131230721;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000b
			public const int actionBarBackgroundColor = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int actionBarTextColor = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int my_Black = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int my_Crimson = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int my_Indianred = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int my_LightGreen = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int my_White = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int my_WhiteSmoke = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int my_blue = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int my_gray = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int my_green = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int my_ivoryblack = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int my_purple = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Border_color = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checkicon1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int checkicon2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int checkicon3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkicon4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int checkicon5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int correcticon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int erroricon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_drawer = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_green_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_orange_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int rect_text_edit = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int rect_text_edit_BLACK = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int rect_text_edit_CRIMSON = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rect_text_edit_GREEN = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rect_text_edit_INDIANRED = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rect_text_edit_IVORYBLACK = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int rect_text_edit_WHITESMOKE = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int selector_color = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int shape_rounded_blue_rect = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int shape_rounded_bothside_blue_rect = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int shape_rounded_bothside_crimson_rect = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int shape_rounded_bothside_indianred_rect = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int shape_rounded_bothside_white_rect = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int shape_rounded_crimson_rect = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int shape_rounded_indianred_rect = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int shape_rounded_white_rect = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int splash = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int user = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a002b
			public const int Age_row = 2131361835;
			
			// aapt resource value: 0x7f0a0001
			public const int Content_frame = 2131361793;
			
			// aapt resource value: 0x7f0a002a
			public const int Flat_row = 2131361834;
			
			// aapt resource value: 0x7f0a0028
			public const int Id_row = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int Name_row = 2131361833;
			
			// aapt resource value: 0x7f0a001a
			public const int NavigationDrawerItem = 2131361818;
			
			// aapt resource value: 0x7f0a0031
			public const int action_submit = 2131361841;
			
			// aapt resource value: 0x7f0a000e
			public const int age = 2131361806;
			
			// aapt resource value: 0x7f0a0024
			public const int autocomplete_edittext_city = 2131361828;
			
			// aapt resource value: 0x7f0a0006
			public const int bSignIn = 2131361798;
			
			// aapt resource value: 0x7f0a0015
			public const int bSignUp = 2131361813;
			
			// aapt resource value: 0x7f0a0007
			public const int checkbox_remember_me = 2131361799;
			
			// aapt resource value: 0x7f0a001c
			public const int drawer_itemName = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int drawer_photo = 2131361819;
			
			// aapt resource value: 0x7f0a0023
			public const int edittext_address = 2131361827;
			
			// aapt resource value: 0x7f0a001e
			public const int edittext_age = 2131361822;
			
			// aapt resource value: 0x7f0a0021
			public const int edittext_email = 2131361825;
			
			// aapt resource value: 0x7f0a001d
			public const int edittext_name = 2131361821;
			
			// aapt resource value: 0x7f0a0020
			public const int edittext_password = 2131361824;
			
			// aapt resource value: 0x7f0a0022
			public const int edittext_phone = 2131361826;
			
			// aapt resource value: 0x7f0a001f
			public const int edittext_username = 2131361823;
			
			// aapt resource value: 0x7f0a0012
			public const int etAge = 2131361810;
			
			// aapt resource value: 0x7f0a0014
			public const int etEmail = 2131361812;
			
			// aapt resource value: 0x7f0a0004
			public const int etUsername = 2131361796;
			
			// aapt resource value: 0x7f0a0011
			public const int etname = 2131361809;
			
			// aapt resource value: 0x7f0a0005
			public const int etpwd = 2131361797;
			
			// aapt resource value: 0x7f0a000d
			public const int flat = 2131361805;
			
			// aapt resource value: 0x7f0a0013
			public const int flatspinner = 2131361811;
			
			// aapt resource value: 0x7f0a0017
			public const int footerView = 2131361815;
			
			// aapt resource value: 0x7f0a0019
			public const int grid = 2131361817;
			
			// aapt resource value: 0x7f0a000b
			public const int id = 2131361803;
			
			// aapt resource value: 0x7f0a0018
			public const int imageView = 2131361816;
			
			// aapt resource value: 0x7f0a002c
			public const int imageview_icon = 2131361836;
			
			// aapt resource value: 0x7f0a0010
			public const int imageview_profile = 2131361808;
			
			// aapt resource value: 0x7f0a003b
			public const int itemAboutus = 2131361851;
			
			// aapt resource value: 0x7f0a0036
			public const int itemCashflow = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int itemDailyExpenses = 2131361845;
			
			// aapt resource value: 0x7f0a0037
			public const int itemEvents = 2131361847;
			
			// aapt resource value: 0x7f0a0038
			public const int itemGallary = 2131361848;
			
			// aapt resource value: 0x7f0a003e
			public const int itemLogout = 2131361854;
			
			// aapt resource value: 0x7f0a0034
			public const int itemMaintainance = 2131361844;
			
			// aapt resource value: 0x7f0a003d
			public const int itemProfile = 2131361853;
			
			// aapt resource value: 0x7f0a0039
			public const int itemRenters = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int itemRules = 2131361850;
			
			// aapt resource value: 0x7f0a0033
			public const int itemUserList = 2131361843;
			
			// aapt resource value: 0x7f0a0003
			public const int leftListView = 2131361795;
			
			// aapt resource value: 0x7f0a000f
			public const int listItems = 2131361807;
			
			// aapt resource value: 0x7f0a003c
			public const int mainMenu = 2131361852;
			
			// aapt resource value: 0x7f0a0000
			public const int myDrawer_layout = 2131361792;
			
			// aapt resource value: 0x7f0a000c
			public const int name = 2131361804;
			
			// aapt resource value: 0x7f0a0032
			public const int pop_List_menu = 2131361842;
			
			// aapt resource value: 0x7f0a0030
			public const int popupbuttonmenuimageView = 2131361840;
			
			// aapt resource value: 0x7f0a0027
			public const int radiobutton_female = 2131361831;
			
			// aapt resource value: 0x7f0a0026
			public const int radiobutton_male = 2131361830;
			
			// aapt resource value: 0x7f0a0025
			public const int radiogroup_gender = 2131361829;
			
			// aapt resource value: 0x7f0a000a
			public const int shMsg = 2131361802;
			
			// aapt resource value: 0x7f0a002e
			public const int textview_content = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int textview_greeting = 2131361839;
			
			// aapt resource value: 0x7f0a002d
			public const int textview_title = 2131361837;
			
			// aapt resource value: 0x7f0a0016
			public const int tvLoginLink = 2131361814;
			
			// aapt resource value: 0x7f0a0008
			public const int tvforget = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int tvregister = 2131361801;
			
			// aapt resource value: 0x7f0a0002
			public const int tvtext = 2131361794;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int item_columns = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_drawer_welcomeLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_register_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int footer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_browse = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NavigationDrawerItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ProfileActivityLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int record_view = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int UserListLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int WelcomeActivityLayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int check_submit = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int popup_List_menu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int popup_menu = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070005
			public const int Drawer_label = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int Flat_prompt = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int Login_label = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int Profile_label = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int Welcome_label = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int close_drawer = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int footer_text = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int open_drawer = 2131165190;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050016
			public const int MyActionBarTheme = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int MyActionBarTheme_ActionBar_TitleTextStyle = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int MyActionBarTheme_ActionBarStyle = 2131034135;
			
			// aapt resource value: 0x7f05000f
			public const int MyBLACKTheme = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int MyBLACKThemewithTitlebar = 2131034133;
			
			// aapt resource value: 0x7f05000c
			public const int MyCRIMSONTheme = 2131034124;
			
			// aapt resource value: 0x7f050012
			public const int MyCRIMSONThemewithTitlebar = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int MyDefaultwhitesmokeTheme = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int MyDefaultwhitesmokeThemewithTitlebar = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int MyGreenTheme = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int MyGreenThemewithTitlebar = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int MyINDIANREDTheme = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int MyINDIANREDThemewithTitlebar = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int MyIVORYBLACKTheme = 2131034126;
			
			// aapt resource value: 0x7f050014
			public const int MyIVORYBLACKThemewithTitlebar = 2131034132;
			
			// aapt resource value: 0x7f050005
			public const int myTextViewStyle_Shape_rounded_bothside_rect = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int myTextViewStyle_Shape_rounded_bothside_rect_BLUE = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int myTextViewStyle_Shape_rounded_bothside_rect_CRIMSON = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int myTextViewStyle_Shape_rounded_bothside_rect_INDIANRED = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int myTextViewStyle_Shape_rounded_bothside_rect_WHITE = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int myTextViewStyle_Shape_rounded_rect = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int myTextViewStyle_Shape_rounded_rect_BLUE = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int myTextViewStyle_Shape_rounded_rect_CRIMSON = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int myTextViewStyle_Shape_rounded_rect_INDIANRED = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int myTextViewStyle_Shape_rounded_rect_WHITE = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
